[versions]
kotlin = "1.9.24"
kotest = "5.5.5"
skippy = "0.0.25"

[libraries]
kotest-framework-api = { group = "io.kotest", name = "kotest-framework-api", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version = "1.13.17" }

skippy-core = { group = "io.skippy", name = "skippy-core", version.ref = "skippy" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
skippy = { id = "io.skippy", version.ref = "skippy" }
